### ISSUE TITLE
complaint/suggestion about computation of standardized.index

### ISSUE THREAD

**Issue by don-git** [WillemMaetens/standaRdized#1]
I think it's unreasonable to assign to zero values qnorm(x["prob.zero"]) since all you know is that this sample is
in that bottom prob.zero.  I think it would make more sense to assign qnorm of half that prob.zero.  As an extreme case, 
if prob.zero is near 1 then I think SPI should be near zero, not near +infinity.
Similarly, in the case where prob.zero is 1, I suggest that even a non-zero value should be assigned not +infinity but
rather something like qnorm of 1 - 1/(2 * #samples), e.g., if there are 10 samples, all zero, you really are only justified
in claiming that this non-zero is in the upper 1/10, and it seems most reasonable to estimate it at 19/20.

**Comment by WillemMaetens** [comment]
Hi, sorry for the late reply. This is a bit of a legacy project, I should pick it up again/check more often what is going on. Yes, you are right that assigning the empirical probability of zero samples to calculate the SPI introduces some problems. To my knowledge, there is no "definite" solution to this, and this package implements the approach that is taken in most literature (e.g. https://core.ac.uk/download/pdf/188114318.pdf, amongst a few others). 

In general, the SPI is only suited to areas (or accumulation periods) with low probabilities of zero rainfall. The empirical treatment of zeros is only there to not have the index "crash" when a zero accumulation occasionally does occur, not to properly analyse the dynamics of zero precipitation. Most applications of SPI mask arid and hyperarid areas with a substantial chance of zero precipitation over one or more months.
